[package]
name = "masque-throughput-benchmark"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[package.metadata.benchy]
id = "masque-throughput"
default = true

[dependencies]
anyhow.workspace = true
benchy-runner.workspace = true
masque-common = { path = "../masque-common" }
tokio.workspace = true
